# -*- coding: utf-8 -*-
"""survey_no.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzlT66oFGHRk5kfAjAK1AR8Ajo57h3vO
"""

import requests
from bs4 import BeautifulSoup

import requests
from bs4 import BeautifulSoup

def get_survey_numbers(district_id, mandal_id, village_id):
    base_url = "https://dharani.telangana.gov.in/knowLandStatus"
    params = {
        'districtID': district_id,
        'mandalID': mandal_id,
        'villageID': village_id
    }
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
    }

    try:
        response = requests.get(base_url, params=params, headers=headers, timeout=60)
        if response.status_code == 200:
            soup = BeautifulSoup(response.content, 'html.parser')
            survey_select = soup.find('select', {'id': 'surveyIdselect'})
            survey_numbers = []
            if survey_select:
                for option in survey_select.find_all('option'):
                    value = option.get('value')
                    if value != '0' and value:
                        survey_numbers.append(value)
            return survey_numbers
        else:
            print(f"Failed to retrieve data. Status code: {response.status_code}")
            return []

    except requests.exceptions.RequestException as e:
        print(f"Connection error: {e}")
        return []

district_id = "3"
mandal_id = "2"
village_id = "23"

survey_numbers = get_survey_numbers(district_id, mandal_id, village_id)

print(f"Survey numbers for District: {district_id}, Mandal: {mandal_id}, Village: {village_id}:")
for survey_number in survey_numbers:
    print(survey_number)